version: '3.8'

networks:
  network:
    #internal: true
    driver: bridge
    name: ${NETWORK}
    enable_ipv6: false
    attachable: true

services:
  apache:
    build:
      context: ./apache
      args:
          PHP_VERSION: '${PHP_VERSION}'
    depends_on:
      - database
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./app:/var/www/html
    networks:
      - network
  database:
    image: mysql:8.0.33
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASS}'
#    ports:
#      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    networks:
      - network
